// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unqdafdzbtgpwlgkepqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucWRhZmR6YnRncHdsZ2tlcHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MDQwNjUsImV4cCI6MjA4OTA4MDA2NX0.YOC-K2Rp6Ns9e4-zKmG6MJh1oIVRtGC3fVBvy5uXZcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});